"""Reviewed Spanish, English and Portuguese administration messages."""

UI_CATALOG = {
    "ui_0008417495": (
        "{p0}\nCuota: USD {p1:.2f} por ciclo de 30 días\nComisión: {p2:g}% de los ingresos gestionados.\nLa factura se emite al cerrar cada ciclo. Si ya tienes un ciclo activo, el cambio se aplica al próximo. Activar un plan termina la prueba gratuita.",
        "{p0}\nFee: USD {p1:.2f} per 30-day cycle\nCommission: {p2:g}% of managed revenue.\nAn invoice is issued at the end of each cycle. If you already have an active cycle, the change applies to the next one. Activating a plan ends the free trial.",
        "{p0}\nTaxa: USD {p1:.2f} por ciclo de 30 dias\nComissão: {p2:g}% da receita gerenciada.\nA fatura é emitida ao fechar cada ciclo. Se já houver um ciclo ativo, a alteração valerá para o próximo. Ativar um plano encerra o teste gratuito.",
    ),
    "ui_004ed97211": (
        "Consulta guardada. El administrador la verá en Soporte de la plataforma.",
        "Question saved. The administrator will see it in Platform support.",
        "Consulta salva. O administrador a verá no Suporte da plataforma.",
    ),
    "ui_00ec16f7a6": ("⭐ Planes", "⭐ Plans", "⭐ Planos"),
    "ui_00fe4fe3ac": (
        "Abrir negocio completo",
        "Open full business account",
        "Abrir conta completa do negócio",
    ),
    "ui_0119803da0": ("Canal", "Channel", "Canal"),
    "ui_016a47d628": (
        "Contenido o acceso digital",
        "Digital content or access",
        "Conteúdo ou acesso digital",
    ),
    "ui_016c1e250b": ("Conceder días / reactivar", "Grant days / reactivate", "Conceder dias / reativar"),
    "ui_021c129c01": ("✅ Aprobar", "✅ Approve", "✅ Aprovar"),
    "ui_03de1ffa78": (
        "Confirma que verificaste el ingreso real y escribe una nota para el historial (mínimo 3 caracteres):",
        "Confirm you verified the actual incoming payment and write a history note (at least 3 characters):",
        "Confirme que verificou o recebimento real e escreva uma nota para o histórico (pelo menos 3 caracteres):",
    ),
    "ui_06b64ed69a": ("🔧 Reparar conexión", "🔧 Repair connection", "🔧 Reparar conexão"),
    "ui_07ba25b943": (
        "Selecciona los canales incluidos en el regalo y confirma la creación.",
        "Select the channels included in the gift and confirm creation.",
        "Selecione os canais incluídos no presente e confirme a criação.",
    ),
    "ui_0834eb5909": (
        "Confirmar devolución registrada",
        "Confirm recorded refund",
        "Confirmar devolução registrada",
    ),
    "ui_091f5af955": ("Conexión cancelada.", "Connection cancelled.", "Conexão cancelada."),
    "ui_09bfe9f654": ("Plan del acceso gratuito:", "Plan for free access:", "Plano do acesso gratuito:"),
    "ui_0ab663183e": ("💱 Conversiones a USD", "💱 Conversions to USD", "💱 Conversões para USD"),
    "ui_0be56afd40": ("Ver progreso", "View progress", "Ver progresso"),
    "ui_0c11b5e195": (
        "Envía la referencia bancaria o el ID de transacción cripto. Puedes adjuntar un comprobante con la referencia en el pie del archivo.",
        "Send the bank reference or crypto transaction ID. You can attach a receipt with the reference in the file caption.",
        "Envie a referência bancária ou o ID da transação cripto. Você pode anexar um comprovante com a referência na legenda do arquivo.",
    ),
    "ui_0c92592dde": ("Renovar manualmente", "Renew manually", "Renovar manualmente"),
    "ui_0c9eb8dbc4": ("Confirmar desconexión", "Confirm disconnection", "Confirmar desconexão"),
    "ui_0cfb8d9e14": (
        "Nombre visible del nuevo bot (máximo 64 caracteres):",
        "Display name of the new bot (up to 64 characters):",
        "Nome exibido do novo bot (até 64 caracteres):",
    ),
    "ui_0d23c5ab80": (
        "\nPrueba gratuita: {p0} días y {p1} horas restantes",
        "\nFree trial: {p0} days and {p1} hours remaining",
        "\nTeste gratuito: restam {p0} dias e {p1} horas",
    ),
    "ui_0e128d2caf": ("💰 Añadir / editar precio", "💰 Add / edit price", "💰 Adicionar / editar preço"),
    "ui_0ed3deb925": (
        "Importe (Stars o centavos)",
        "Amount (Stars or minor currency units)",
        "Valor (Stars ou unidades mínimas da moeda)",
    ),
    "ui_0efc143111": ("Estado: ", "Status: ", "Estado: "),
    "ui_0fb4618723": ("Vence", "Expires", "Vence"),
    "ui_101d0950b1": (
        "Escribe el mensaje de la campaña (se guardará como borrador):",
        "Write the campaign message (it will be saved as a draft):",
        "Escreva a mensagem da campanha (será salva como rascunho):",
    ),
    "ui_10dc87abb5": ("Importe en ", "Amount in ", "Valor em "),
    "ui_1202515e3b": (
        "Tu acceso de administrador fue retirado. El formulario se canceló.",
        "Your administrator access was removed. The form was cancelled.",
        "Seu acesso de administrador foi removido. O formulário foi cancelado.",
    ),
    "ui_137cb944c5": ("Etiquetas", "Tags", "Etiquetas"),
    "ui_13d855b4c7": (
        "Ya pagué: enviar referencia",
        "Already paid: submit reference",
        "Já paguei: enviar referência",
    ),
    "ui_140fe22b91": ("🏷 Etiquetas", "🏷 Tags", "🏷 Etiquetas"),
    "ui_160bab02ef": (
        "Mensajes del bot. Variables permitidas según el texto original.",
        "Bot messages. Supported variables depend on the original template.",
        "Mensagens do bot. As variáveis permitidas dependem do modelo original.",
    ),
    "ui_170615fe9b": (
        "Configura los cobros de este negocio. Para accesos y productos digitales dentro de Telegram se utiliza Stars.",
        "Set up payments for this business. Digital products and access inside Telegram use Stars.",
        "Configure os pagamentos deste negócio. Produtos e acessos digitais dentro do Telegram usam Stars.",
    ),
    "ui_17a000019b": ("Descargar CSV", "Download CSV", "Baixar CSV"),
    "ui_17fd6b8557": ("Siguiente →", "Next →", "Próximo →"),
    "ui_182239eaa0": (
        "¿Cómo se llama tu negocio? (2 a 100 caracteres)",
        "What is your business called? (2 to 100 characters)",
        "Qual é o nome do seu negócio? (2 a 100 caracteres)",
    ),
    "ui_183a5d0206": (
        "Confirma la nueva cuota USD {p0:.2f} y comisión {p1:g}% para ciclos nuevos.\nMotivo: {p2}",
        "Confirm the new USD {p0:.2f} fee and {p1:g}% commission for new cycles.\nReason: {p2}",
        "Confirme a nova taxa USD {p0:.2f} e comissão de {p1:g}% para ciclos novos.\nMotivo: {p2}",
    ),
    "ui_186cac41fa": (
        "Renovación cancelada. El ciclo actual se conserva hasta su fecha de fin.",
        "Renewal cancelled. The current cycle remains valid until its end date.",
        "Renovação cancelada. O ciclo atual continua válido até a data final.",
    ),
    "ui_19c9a8553f": ("Usuario VIP", "VIP user", "Usuário VIP"),
    "ui_1a67f8860c": ("\nPagos presentados:\n", "\nSubmitted payments:\n", "\nPagamentos enviados:\n"),
    "ui_1a92b3d907": ("Comprobante para revisión", "Receipt for review", "Comprovante para revisão"),
    "ui_1aa187550f": (
        "Zona horaria IANA (ejemplo America/La_Paz):",
        "IANA time zone (example America/La_Paz):",
        "Fuso horário IANA (exemplo America/La_Paz):",
    ),
    "ui_1b32f4ae07": ("Titular", "Account holder", "Titular"),
    "ui_1bb0a4e79f": ("Confirmaciones del proveedor", "Provider confirmations", "Confirmações do provedor"),
    "ui_1bba71a511": ("Creado", "Created", "Criado"),
    "ui_1bc1d359df": ("Plan activado desde ", "Plan active from ", "Plano ativo a partir de "),
    "ui_1cb349623e": ("Días de tolerancia", "Grace period in days", "Dias de tolerância"),
    "ui_1d82a0d93a": (
        "Usuario del bot sin @; debe terminar en bot. Ejemplo: MiClubPremium_bot",
        "Bot username without @; it must end in bot. Example: MyPremiumClub_bot",
        "Usuário do bot sem @; deve terminar em bot. Exemplo: MeuClubePremium_bot",
    ),
    "ui_1de0f3b980": (
        "Envía una foto JPG, PNG o WebP (máximo 5 MB).",
        "Send a JPG, PNG or WebP photo (up to 5 MB).",
        "Envie uma foto JPG, PNG ou WebP (até 5 MB).",
    ),
    "ui_1ea442a134": ("No", "No", "Não"),
    "ui_1fb05be40b": ("Respuesta en cola.", "Reply queued.", "Resposta na fila."),
    "ui_20c6e9949d": ("Confirmar condiciones", "Confirm terms", "Confirmar condições"),
    "ui_212e06c386": ("Acción", "Action", "Ação"),
    "ui_21310cfee5": ("Automatización activada.", "Automation enabled.", "Automação ativada."),
    "ui_217cc273b5": ("Confirmar cambio", "Confirm change", "Confirmar alteração"),
    "ui_2243b05641": ("Última actividad", "Last activity", "Última atividade"),
    "ui_22cd26baf8": ("📝 Contenido", "📝 Content", "📝 Conteúdo"),
    "ui_2371c7c6d6": (
        "\nImporte pagado: 0 · acceso gratuito",
        "\nPaid amount: 0 · free access",
        "\nValor pago: 0 · acesso gratuito",
    ),
    "ui_238c54ad69": ("Añadir al canal", "Add to channel", "Adicionar ao canal"),
    "ui_2637e9e48b": (
        "Días de acceso que quieres conceder sin cobro (1 a 365):",
        "Days of free access to grant (1 to 365):",
        "Dias de acesso gratuito a conceder (1 a 365):",
    ),
    "ui_26499f4e77": (
        "Este pago incluye una referencia de transacción, sin archivo adjunto.",
        "This payment includes a transaction reference with no attachment.",
        "Este pagamento inclui uma referência de transação sem anexo.",
    ),
    "ui_26a4a8b2bd": (
        "Configura dónde recibir los pagos de TU plataforma. Los métodos de los negocios se configuran en cada bot.",
        "Set up where YOUR platform receives payments. Business payment methods are configured in each bot.",
        "Configure onde SUA plataforma recebe pagamentos. Os métodos de pagamento dos negócios são configurados em cada bot.",
    ),
    "ui_27614b5893": (
        "✅ Comprobación solicitada. Te avisaremos aquí cuando termine.",
        "✅ Check requested. We will notify you here when it finishes.",
        "✅ Verificação solicitada. Avisaremos aqui quando terminar.",
    ),
    "ui_2855722d72": ("🏦 Instrucciones de cobro", "🏦 Payment instructions", "🏦 Instruções de pagamento"),
    "ui_2941dd7b25": (
        "{p0} actual:\n{p1}\n\nEnvía el nuevo texto:",
        "Current {p0}:\n{p1}\n\nSend the new text:",
        "{p0} atual:\n{p1}\n\nEnvie o novo texto:",
    ),
    "ui_2990fad4a1": ("⏱ Crear automatización", "⏱ Create automation", "⏱ Criar automação"),
    "ui_29e7e810a3": ("Usuario de soporte", "Support username", "Usuário de suporte"),
    "ui_2a16b4b4c8": (
        "Paso 7/7 · Comprobar y publicar",
        "Step 7/7 · Check and publish",
        "Etapa 7/7 · Verificar e publicar",
    ),
    "ui_2a1b0bdc1f": ("Responder al creador", "Reply to creator", "Responder ao criador"),
    "ui_2ad9d2c41c": ("💳 Mi cuenta SaaS", "💳 My SaaS account", "💳 Minha conta SaaS"),
    "ui_2b17081bee": (
        "🏢 Negocios y acceso completo",
        "🏢 Businesses and full access",
        "🏢 Negócios e acesso completo",
    ),
    "ui_2c76fd9a05": ("Confirmar reembolso", "Confirm refund", "Confirmar reembolso"),
    "ui_2cc34f66e4": ("Confirma el cambio: ", "Confirm the change: ", "Confirme a alteração: "),
    "ui_2d464981a8": ("Automatización desactivada.", "Automation disabled.", "Automação desativada."),
    "ui_2de59a82f0": ("👤 Equipo", "👤 Team", "👤 Equipe"),
    "ui_2e43abe84e": (
        "💳 {p0}\n{p1}\n{p2}\nSaldo reembolsable: {p3}",
        "💳 {p0}\n{p1}\n{p2}\nRefundable balance: {p3}",
        "💳 {p0}\n{p1}\n{p2}\nSaldo reembolsável: {p3}",
    ),
    "ui_2e76cd740b": ("📢 Conectar canal", "📢 Connect channel", "📢 Conectar canal"),
    "ui_2ebe8a44d3": ("Ajuste o descuento", "Adjustment or discount", "Ajuste ou desconto"),
    "ui_2ef68536d8": ("Pendiente", "Pending", "Pendente"),
    "ui_2f774e1044": ("Cambiar rol", "Change role", "Alterar função"),
    "ui_2fae6b0900": (
        "Resolver conversiones pendientes",
        "Resolve pending conversions",
        "Resolver conversões pendentes",
    ),
    "ui_2fc3433b01": ("📄 Facturas e historial", "📄 Invoices and history", "📄 Faturas e histórico"),
    "ui_300673ea40": (
        "✅ Plan creado y Stars habilitado. Completa soporte y políticas antes de publicar.",
        "✅ Plan created and Stars enabled. Complete support and policies before publishing.",
        "✅ Plano criado e Stars ativado. Complete suporte e políticas antes de publicar.",
    ),
    "ui_3036726cc4": (
        "Nombre de tu negocio (2 a 100 caracteres):",
        "Business name (2 to 100 characters):",
        "Nome do negócio (2 a 100 caracteres):",
    ),
    "ui_303acc5bdc": (
        "🎁 Activar prueba gratuita de 3 días",
        "🎁 Start 3-day free trial",
        "🎁 Iniciar teste gratuito de 3 dias",
    ),
    "ui_3120002bbd": ("🖼 Foto de perfil", "🖼 Profile photo", "🖼 Foto de perfil"),
    "ui_3134bc7741": ("permisos del canal", "channel permissions", "permissões do canal"),
    "ui_32b6efc666": (
        "Formato de fecha: DMY, MDY o YMD",
        "Date format: DMY, MDY or YMD",
        "Formato de data: DMY, MDY ou YMD",
    ),
    "ui_336d23d99f": (
        "Canales incluidos en nuevas suscripciones. Los accesos existentes conservan su configuración.",
        "Channels included in new subscriptions. Existing access keeps its original configuration.",
        "Canais incluídos em novas assinaturas. Os acessos existentes mantêm a configuração original.",
    ),
    "ui_33b2578969": ("Periodo personalizado", "Custom period", "Período personalizado"),
    "ui_33c12ac706": ("Revisión guardada.", "Review saved.", "Revisão salva."),
    "ui_340317c5fc": ("📊 Resumen de plataforma", "📊 Platform overview", "📊 Resumo da plataforma"),
    "ui_340553986a": (
        "Verifiqué el ingreso: aprobar",
        "Incoming payment verified: approve",
        "Recebimento verificado: aprovar",
    ),
    "ui_3551ca3347": ("Notificaciones y resúmenes", "Notifications and summaries", "Notificações e resumos"),
    "ui_357eaf7f92": ("💰 Pagos SaaS", "💰 SaaS payments", "💰 Pagamentos SaaS"),
    "ui_3651a93138": ("Precio en Stars (entero):", "Price in Stars (integer):", "Preço em Stars (inteiro):"),
    "ui_37fccdea61": ("Cupones", "Coupons", "Cupons"),
    "ui_38e9bd3a1f": (
        "Acceso de equipo configurado.",
        "Team access configured.",
        "Acesso da equipe configurado.",
    ),
    "ui_38f5f5f9fa": ("\nMotivo: ", "\nReason: ", "\nMotivo: "),
    "ui_3925a92fe9": (
        "Dato no válido. Revisa el formato indicado.",
        "Invalid value. Check the requested format.",
        "Valor inválido. Verifique o formato solicitado.",
    ),
    "ui_39ba83d8c9": (
        "Importe abonado en USD (admite pagos parciales). En cripto, indica el equivalente USD que solicitas acreditar; el administrador comprobará el ingreso y la conversión.",
        "Amount paid in USD (partial payments allowed). For crypto, enter the USD equivalent you want credited; the administrator will verify receipt and conversion.",
        "Valor pago em USD (permite pagamentos parciais). Em cripto, informe o equivalente em USD que deseja creditar; o administrador verificará o recebimento e a conversão.",
    ),
    "ui_39d54e1a49": ("Formato de fecha", "Date format", "Formato de data"),
    "ui_3a32ca0d5d": ("Intentos", "Attempts", "Tentativas"),
    "ui_3aa941210f": (
        "plan activo con precio Stars",
        "active plan with a Stars price",
        "plano ativo com preço em Stars",
    ),
    "ui_3e5dac6074": ("Nuevo plan:", "New plan:", "Novo plano:"),
    "ui_3eef234094": (
        "Describe tu consulta o el problema con tu pago (5 a 3000 caracteres).",
        "Describe your question or payment problem (5 to 3000 characters).",
        "Descreva sua dúvida ou problema com o pagamento (5 a 3000 caracteres).",
    ),
    "ui_3fc99777fe": (
        "Selecciona el dato que quieres cambiar.",
        "Select the field you want to change.",
        "Selecione o campo que deseja alterar.",
    ),
    "ui_40a27aafae": (
        "Cancelar detiene la renovación al finalizar el ciclo actual. Las facturas pendientes siguen debiéndose y tus datos se conservan.",
        "Cancellation stops renewal at the end of the current cycle. Outstanding invoices remain due and your data is preserved.",
        "O cancelamento interrompe a renovação ao final do ciclo atual. As faturas pendentes continuam devidas e seus dados são mantidos.",
    ),
    "ui_40f8e79a34": (
        "🤖 @{p0}\n{p1}\nEstado: {p2}\nPublicado: {p3}",
        "🤖 @{p0}\n{p1}\nStatus: {p2}\nPublished: {p3}",
        "🤖 @{p0}\n{p1}\nEstado: {p2}\nPublicado: {p3}",
    ),
    "ui_426234e72a": ("Detalle", "Details", "Detalhes"),
    "ui_4290938ed5": ("Personalizado", "Custom", "Personalizado"),
    "ui_4371521949": ("Iniciar / reanudar", "Start / resume", "Iniciar / retomar"),
    "ui_4397348d23": (
        "\nEl valor se guardará cifrado y no volverá a mostrarse.",
        "\nThe value will be stored encrypted and will not be displayed again.",
        "\nO valor será armazenado criptografado e não será exibido novamente.",
    ),
    "ui_43b228654b": ("Zona horaria", "Time zone", "Fuso horário"),
    "ui_44adcb1e8a": (
        "\nEl propietario debe completar las instrucciones de cobro. Contacta soporte.",
        "\nThe platform owner needs to complete payment instructions. Contact support.",
        "\nO proprietário da plataforma precisa completar as instruções de pagamento. Contate o suporte.",
    ),
    "ui_44f9bcc469": ("Reactivar", "Reactivate", "Reativar"),
    "ui_46c7714c73": ("🤖 Bots", "🤖 Bots", "🤖 Bots"),
    "ui_46ce881775": (
        "\nPuedes reintentar o usar /cancel.",
        "\nYou can try again or use /cancel.",
        "\nVocê pode tentar novamente ou usar /cancel.",
    ),
    "ui_46ce94d702": (
        "\nComisión: pendiente de conversión",
        "\nCommission: currency conversion pending",
        "\nComissão: conversão de moeda pendente",
    ),
    "ui_473aed05f7": ("✅ Guardar permisos", "✅ Save permissions", "✅ Salvar permissões"),
    "ui_476509665c": (
        "Escribe la respuesta que se enviará al cliente desde su bot:",
        "Write the reply to send to the customer from their bot:",
        "Escreva a resposta que será enviada ao cliente pelo bot:",
    ),
    "ui_48c7cde407": ("Webhook signing secret", "Webhook signing secret", "Segredo de assinatura do webhook"),
    "ui_48fb6aa3f9": (
        "📊 Consultando la actividad y las finanzas de tu plataforma…",
        "📊 Loading your platform's activity and finances…",
        "📊 Consultando a atividade e as finanças da sua plataforma…",
    ),
    "ui_4907281581": ("Paso 2/7 · Canal", "Step 2/7 · Channel", "Etapa 2/7 · Canal"),
    "ui_49cffbf85a": ("Asunto", "Subject", "Assunto"),
    "ui_4a00a6a4ca": (
        "Motivo del cambio de suscripción:",
        "Reason for changing the subscription:",
        "Motivo da alteração da assinatura:",
    ),
    "ui_4a34e7e770": (
        "Todavía no se recibió ningún canal. Añade el bot como administrador y vuelve a verificar.",
        "No channel received yet. Add the bot as an administrator and check again.",
        "Nenhum canal recebido. Adicione o bot como administrador e verifique novamente.",
    ),
    "ui_4a6ec008ac": ("👁 Ver comprobante", "👁 View receipt", "👁 Ver comprovante"),
    "ui_4a6f1afd1a": ("📋 Auditoría", "📋 Audit", "📋 Auditoria"),
    "ui_4a756c24fe": ("👥 Clientes", "👥 Customers", "👥 Clientes"),
    "ui_4aded5faf1": ("Client secret", "Client secret", "Segredo do cliente"),
    "ui_4b667ee7b5": (
        "\nConversión pendiente: ",
        "\nCurrency conversion pending: ",
        "\nConversão de moeda pendente: ",
    ),
    "ui_4bb3897f18": ("⚙️ Cola y errores", "⚙️ Queue and errors", "⚙️ Fila e erros"),
    "ui_4bc296eeb5": ("Nunca compraron", "Never purchased", "Nunca compraram"),
    "ui_4bdd388b44": ("Plan específico", "Specific plan", "Plano específico"),
    "ui_4cf7d4f76d": ("🚀 Crear mi negocio", "🚀 Create my business", "🚀 Criar meu negócio"),
    "ui_4d0c997ac7": ("Responder al cliente", "Reply to customer", "Responder ao cliente"),
    "ui_4de0ad27ba": ("👥 Audiencia", "👥 Audience", "👥 Público"),
    "ui_4e50ea9483": ("Producto físico", "Physical product", "Produto físico"),
    "ui_4e5a0f2f0f": (
        "Confirma que la devolución bancaria ya se realizó: ",
        "Confirm that the bank refund was already completed: ",
        "Confirme que a devolução bancária já foi realizada: ",
    ),
    "ui_4ea54faa94": ("Duración (días)", "Duration (days)", "Duração (dias)"),
    "ui_4ed786ebd4": ("Transferencia", "Bank transfer", "Transferência"),
    "ui_4f0aa24a46": ("Precio actualizado.", "Price updated.", "Preço atualizado."),
    "ui_4fc874c44c": ("Último error", "Last error", "Último erro"),
    "ui_50b6359219": (
        "🛡 Administración de la plataforma\nCuentas, conexiones, pruebas, facturas y actividad.",
        "🛡 Platform administration\nAccounts, connections, trials, invoices and activity.",
        "🛡 Administração da plataforma\nContas, conexões, testes, faturas e atividade.",
    ),
    "ui_50e7acc820": ("Comprobar permisos", "Check permissions", "Verificar permissões"),
    "ui_52233e2c4d": ("Privacidad", "Privacy", "Privacidade"),
    "ui_522438169f": ("Uso del plan", "Plan usage", "Uso do plano"),
    "ui_5287b483b3": (
        "\nTodavía no se cerró ningún ciclo.",
        "\nNo cycle has closed yet.",
        "\nNenhum ciclo foi fechado ainda.",
    ),
    "ui_52ee5f657f": ("Mes anterior", "Previous month", "Mês anterior"),
    "ui_53342e5e73": ("✅ Comprobar y publicar", "✅ Check and publish", "✅ Verificar e publicar"),
    "ui_533d8437e1": ("Registros de plataforma", "Platform records", "Registros da plataforma"),
    "ui_5449339399": (
        "Nuevo precio en Stars, entero entre 1 y 10000. Los pagos ya iniciados conservan su precio.",
        "New Stars price, an integer from 1 to 10000. Payments already started keep their price.",
        "Novo preço em Stars, um inteiro entre 1 e 10000. Pagamentos já iniciados mantêm seu preço.",
    ),
    "ui_54a0560489": ("Configurado", "Configured", "Configurado"),
    "ui_55133d4e6e": ("Hoy", "Today", "Hoje"),
    "ui_555fe228de": ("Añadir nota", "Add note", "Adicionar nota"),
    "ui_5576f4187b": ("\nPróximo ciclo: ", "\nNext cycle: ", "\nPróximo ciclo: "),
    "ui_562bb15757": ("Nombre", "Name", "Nome"),
    "ui_5685e1faf0": ("Reanudar", "Resume", "Retomar"),
    "ui_5729e3bd27": (
        "Enviar «{p0}» a los contactos que aceptaron campañas:\n\n{p1}",
        "Send “{p0}” to contacts who opted in to campaigns:\n\n{p1}",
        "Enviar «{p0}» aos contatos que aceitaram campanhas:\n\n{p1}",
    ),
    "ui_572a3acfd9": ("Importe", "Amount", "Valor"),
    "ui_57766b9ace": ("🪙 Cripto: ", "🪙 Crypto: ", "🪙 Cripto: "),
    "ui_5a21795626": ("Política de reembolso", "Refund policy", "Política de reembolso"),
    "ui_5a21a58609": ("Retirar acceso", "Remove access", "Remover acesso"),
    "ui_5aa3c084f9": ("Reembolso registrado.", "Refund recorded.", "Reembolso registrado."),
    "ui_5af6139fd1": ("Pedir nuevo", "Request another", "Solicitar outro"),
    "ui_5b50af8895": ("Sin suscripción activa", "Without active subscription", "Sem assinatura ativa"),
    "ui_5b6dba0100": (
        "Condiciones actualizadas para ciclos nuevos. Los ciclos existentes conservan su cuota y comisión.",
        "Terms updated for new cycles. Existing cycles keep their fee and commission.",
        "Condições atualizadas para ciclos novos. Os ciclos existentes mantêm sua taxa e comissão.",
    ),
    "ui_5b832c4889": ("Entorno: sandbox / live", "Environment: sandbox / live", "Ambiente: sandbox / live"),
    "ui_5c451c14a5": ("Plan creado", "Plan created", "Plano criado"),
    "ui_5d5802aec7": (
        "📊 Consultando los datos de tu negocio…",
        "📊 Loading your business data…",
        "📊 Consultando os dados do seu negócio…",
    ),
    "ui_5dc31bd11a": ("Indica ", "Enter ", "Informe "),
    "ui_5e185983b6": ("📄 Facturas SaaS", "📄 SaaS invoices", "📄 Faturas SaaS"),
    "ui_5e5ec188b4": ("\nEtiquetas: ", "\nTags: ", "\nEtiquetas: "),
    "ui_5ef2eb0549": (
        "El bot dejará de ser operado por esta plataforma. Los clientes, pagos y configuraciones permanecerán guardados. Para revocar completamente el acceso del token, usa BotFather.",
        "The platform will stop operating this bot. Customers, payments and settings will remain saved. Use BotFather to fully revoke the token's access.",
        "A plataforma deixará de operar este bot. Clientes, pagamentos e configurações permanecerão salvos. Use BotFather para revogar completamente o acesso do token.",
    ),
    "ui_603739e617": (
        "ID numérico de Telegram del administrador:",
        "Administrator's numeric Telegram ID:",
        "ID numérico do Telegram do administrador:",
    ),
    "ui_60c3c3602d": ("Nota interna guardada.", "Internal note saved.", "Nota interna salva."),
    "ui_60eaf1f65f": ("Términos", "Terms", "Termos"),
    "ui_6133ac78fb": (
        "Volver a comprobar con el proveedor",
        "Check with the provider again",
        "Verificar novamente com o provedor",
    ),
    "ui_61f400df33": (
        "Decisión: {p0}\nMotivo: {p1}",
        "Decision: {p0}\nReason: {p1}",
        "Decisão: {p0}\nMotivo: {p1}",
    ),
    "ui_623ae6a865": (
        "🔗 Invitación\n{p0}\nUsos: {p1}/{p2}\nDuración de acceso: {p3} días\nActiva: {p4}\nNota: {p5}\nVence el enlace: {p6}\nCreada: {p7}\nCreador: {p8}\nCanales: {p9}",
        "🔗 Invitation\n{p0}\nUses: {p1}/{p2}\nAccess duration: {p3} days\nActive: {p4}\nNote: {p5}\nLink expires: {p6}\nCreated: {p7}\nCreator: {p8}\nChannels: {p9}",
        "🔗 Convite\n{p0}\nUsos: {p1}/{p2}\nDuração do acesso: {p3} dias\nAtivo: {p4}\nNota: {p5}\nO link vence: {p6}\nCriado: {p7}\nCriador: {p8}\nCanais: {p9}",
    ),
    "ui_6258023058": ("Pago fallido", "Failed payment", "Pagamento falhou"),
    "ui_63614ffde2": ("Usuario", "User", "Usuário"),
    "ui_6454473998": (
        "Precio total en Stars (entero, 1 a 10000):",
        "Total price in Stars (integer, 1 to 10000):",
        "Preço total em Stars (inteiro, 1 a 10000):",
    ),
    "ui_65d23c6308": ("Suscripción vencida", "Expired subscription", "Assinatura vencida"),
    "ui_65e5fa97d0": ("Verificar bot maestro", "Verify master bot", "Verificar bot principal"),
    "ui_67e865c7ff": ("Tu ID de Telegram: {p0}", "Your Telegram ID: {p0}", "Seu ID do Telegram: {p0}"),
    "ui_67ee24434b": (
        "Planes mensuales de la plataforma. El pago se confirma en Telegram Stars.",
        "Monthly platform plans. Payment is confirmed in Telegram Stars.",
        "Planos mensais da plataforma. O pagamento é confirmado em Telegram Stars.",
    ),
    "ui_68268f3e43": ("Nuevo comprobante", "New receipt", "Novo comprovante"),
    "ui_682e4d9e00": ("Vencen esta semana", "Expire this week", "Vencem esta semana"),
    "ui_68b5d8cd50": ("Preparando comprobante.", "Preparing receipt.", "Preparando comprovante."),
    "ui_6918ce851a": ("Cambiar precio", "Change price", "Alterar preço"),
    "ui_69bf39552a": (
        "{p0}: USD {p1:.2f} + {p2:g}%\nIntroduce cuota USD, porcentaje y motivo. Ejemplo: 30 4 Condiciones comerciales\nSolo afecta a ciclos nuevos.",
        "{p0}: USD {p1:.2f} + {p2:g}%\nEnter USD fee, percentage and reason. Example: 30 4 Commercial terms\nApplies only to new cycles.",
        "{p0}: USD {p1:.2f} + {p2:g}%\nInforme taxa USD, percentual e motivo. Exemplo: 30 4 Condições comerciais\nAplica-se apenas a ciclos novos.",
    ),
    "ui_6a0f01c5a8": (
        "\nSaldo facturado pendiente: USD {p0:.2f}",
        "\nOutstanding invoiced balance: USD {p0:.2f}",
        "\nSaldo faturado pendente: USD {p0:.2f}",
    ),
    "ui_6a2693a2fc": ("Campaña ", "Campaign ", "Campanha "),
    "ui_6bb777626f": ("✅ Activo", "✅ Active", "✅ Ativo"),
    "ui_6bc9a517bf": (
        "Duración del acceso, máximo de usos y días de vigencia del enlace. Ejemplo: 30 10 7\nDespués puedes añadir una nota interna.",
        "Access duration, maximum uses and link validity in days. Example: 30 10 7\nYou can add an internal note after these numbers.",
        "Duração do acesso, limite de usos e validade do link em dias. Exemplo: 30 10 7\nVocê pode adicionar uma nota interna após os números.",
    ),
    "ui_6c0890281b": ("sin precio", "no price", "sem preço"),
    "ui_6c4913e8ec": (
        "Este botón caducó o ya fue utilizado. Abre /start para actualizar el menú.",
        "This button expired or was already used. Open /start to refresh the menu.",
        "Este botão expirou ou já foi usado. Abra /start para atualizar o menu.",
    ),
    "ui_6dced01048": (
        "Tolerancia guardada. Las facturas ya emitidas conservan su vencimiento.",
        "Grace period saved. Already issued invoices keep their due date.",
        "Tolerância salva. Faturas já emitidas mantêm seu vencimento.",
    ),
    "ui_6e81e31a40": ("QR (enviar imagen)", "QR (send image)", "QR (enviar imagem)"),
    "ui_6e957e2354": ("➕ Crear plan", "➕ Create plan", "➕ Criar plano"),
    "ui_6ed4641fe9": ("Servicio presencial", "In-person service", "Serviço presencial"),
    "ui_6f8897827f": (
        "Bot desconectado. Conservamos su historial.",
        "Bot disconnected. Its history is preserved.",
        "Bot desconectado. Seu histórico foi mantido.",
    ),
    "ui_7148fc85af": ("Historial de usos", "Usage history", "Histórico de usos"),
    "ui_71695c21b6": ("Método de pago", "Payment method", "Método de pagamento"),
    "ui_71873019a2": (
        "Facturación y pagos SaaS",
        "SaaS billing and payments",
        "Faturamento e pagamentos SaaS",
    ),
    "ui_719dcdb45d": ("Métodos de pago", "Payment methods", "Métodos de pagamento"),
    "ui_71acd99484": ("Respuesta de soporte:\n", "Support reply:\n", "Resposta do suporte:\n"),
    "ui_723858144b": ("Activo", "Active", "Ativo"),
    "ui_7291eac1c1": ("\nCiclo: {p0} → {p1}", "\nCycle: {p0} → {p1}", "\nCiclo: {p0} → {p1}"),
    "ui_72f47df8c3": ("Suspender", "Suspend", "Suspender"),
    "ui_732040bbac": (
        "\nCuota del ciclo: USD {p0:.2f}",
        "\nCycle fixed fee: USD {p0:.2f}",
        "\nTaxa fixa do ciclo: USD {p0:.2f}",
    ),
    "ui_7392158895": ("Sí", "Yes", "Sim"),
    "ui_7398551db8": (
        "Paso 5/7 · Mensajes y políticas",
        "Step 5/7 · Messages and policies",
        "Etapa 5/7 · Mensagens e políticas",
    ),
    "ui_7485baa288": (
        "conceder {p0} días sin cobro",
        "grant {p0} days at no charge",
        "conceder {p0} dias sem cobrança",
    ),
    "ui_74adda1f31": (
        "Buscar por nombre, usuario o ID",
        "Search by name, username or ID",
        "Buscar por nome, usuário ou ID",
    ),
    "ui_74f3c61f2d": (
        "Hasta cuatro botones, uno por línea: Texto | https://destino. Envía - para quitar los botones.",
        "Up to four buttons, one per line: Text | https://destination. Send - to remove buttons.",
        "Até quatro botões, um por linha: Texto | https://destino. Envie - para remover os botões.",
    ),
    "ui_75702fe412": ("📢 Canales", "📢 Channels", "📢 Canais"),
    "ui_757e7b714c": (
        "Motivo de suspensión (mínimo 5 caracteres):",
        "Reason for suspension (at least 5 characters):",
        "Motivo da suspensão (mínimo de 5 caracteres):",
    ),
    "ui_77bbf98bcc": (
        "Configurar cuota y comisión USD",
        "Set USD fee and commission",
        "Configurar taxa e comissão em USD",
    ),
    "ui_780b2bad8c": (
        "📦 {p0}\n{p1}\n{p2} días\n",
        "📦 {p0}\n{p1}\n{p2} days\n",
        "📦 {p0}\n{p1}\n{p2} dias\n",
    ),
    "ui_7a60f3a8f4": (
        "¿Renovación automática? Escribe sí o no. Solo está disponible con duración de 30 días.",
        "Automatic renewal? Enter yes or no. Available only for a 30-day duration.",
        "Renovação automática? Digite sim ou não. Disponível apenas para duração de 30 dias.",
    ),
    "ui_7aa4c52172": ("Renovación automática", "Automatic renewal", "Renovação automática"),
    "ui_7af7a2be50": ("🪙 Cripto", "🪙 Crypto", "🪙 Cripto"),
    "ui_7b08c54989": (
        "Escribe el recordatorio que se enviará tres días antes de vencer una membresía:",
        "Write the reminder to send three days before a membership expires:",
        "Escreva o lembrete que será enviado três dias antes de uma assinatura vencer:",
    ),
    "ui_7b30e6bee5": ("Paso 6/7 · Idioma", "Step 6/7 · Language", "Etapa 6/7 · Idioma"),
    "ui_7b4919a546": ("suspender: ", "suspend: ", "suspender: "),
    "ui_7c5d0619a4": ("Permisos personalizados", "Custom permissions", "Permissões personalizadas"),
    "ui_7ca527beee": (
        "\nComisión acumulada: USD {p0:.2f}",
        "\nAccrued commission: USD {p0:.2f}",
        "\nComissão acumulada: USD {p0:.2f}",
    ),
    "ui_7cc6d15c23": (
        "Permisos de este administrador:",
        "Permissions for this administrator:",
        "Permissões deste administrador:",
    ),
    "ui_7cfe980e93": (
        "💳 Tu cuenta SaaS\n{p0}: USD {p1:.2f}/30 días + {p2:g}%\nEstado: {p3}",
        "💳 Your SaaS account\n{p0}: USD {p1:.2f}/30 days + {p2:g}%\nStatus: {p3}",
        "💳 Sua conta SaaS\n{p0}: USD {p1:.2f}/30 dias + {p2:g}%\nEstado: {p3}",
    ),
    "ui_7d1b7d9be1": (
        "Nombre, @usuario o ID de Telegram:",
        "Name, @username or Telegram ID:",
        "Nome, @usuário ou ID do Telegram:",
    ),
    "ui_7d3cadebec": ("💳 Cobros", "💳 Captures", "💳 Cobranças"),
    "ui_7d4d0bdd1d": (
        "Escribe el motivo o referencia bancaria de tu decisión:",
        "Write the reason or bank reference for your decision:",
        "Escreva o motivo ou a referência bancária da sua decisão:",
    ),
    "ui_7d8ea9f63f": ("Fin de prueba", "Trial end", "Fim do teste"),
    "ui_7d97958d69": ("Reembolsar cobro", "Refund charge", "Reembolsar cobrança"),
    "ui_7eb3af2fa0": (
        "Duración en días (1 a 3650):",
        "Duration in days (1 to 3650):",
        "Duração em dias (1 a 3650):",
    ),
    "ui_7ef1cd2d34": ("Desactivar", "Disable", "Desativar"),
    "ui_7f8b2e2013": ("Acceso retirado.", "Access removed.", "Acesso removido."),
    "ui_7ff35f0ced": ("Reporte CSV", "CSV report", "Relatório CSV"),
    "ui_7ffe3151d2": (
        "Precio mensual en Stars (1 a 10000):",
        "Monthly price in Stars (1 to 10000):",
        "Preço mensal em Stars (1 a 10000):",
    ),
    "ui_81ed84007e": ("Beneficios", "Benefits", "Benefícios"),
    "ui_827530dd70": ("Desactivar / activar", "Disable / enable", "Desativar / ativar"),
    "ui_836e14df94": ("Confirmar revisión", "Confirm review", "Confirmar revisão"),
    "ui_839add3733": (
        "✅ Activar / programar este plan",
        "✅ Activate / schedule this plan",
        "✅ Ativar / agendar este plano",
    ),
    "ui_83e6b6a593": ("🔧 Reintentar configuración", "🔧 Retry setup", "🔧 Tentar configuração novamente"),
    "ui_83fb2f2268": (
        "💳 Facturación SaaS y comisiones",
        "💳 SaaS billing and commissions",
        "💳 Faturamento SaaS e comissões",
    ),
    "ui_86b8fce623": (
        "Pago {p0}\nMétodo: {p1}\nReferencia: {p2}\nImporte declarado: USD {p3:.2f}\nEstado: {p4}\nNota de revisión: {p5}\n",
        "Payment {p0}\nMethod: {p1}\nReference: {p2}\nDeclared amount: USD {p3:.2f}\nStatus: {p4}\nReview note: {p5}\n",
        "Pagamento {p0}\nMétodo: {p1}\nReferência: {p2}\nValor declarado: USD {p3:.2f}\nEstado: {p4}\nNota de revisão: {p5}\n",
    ),
    "ui_8726db0139": ("Client ID", "Client ID", "ID do cliente"),
    "ui_875aaa7522": (
        "\n⚠️ El comprobante está marcado como sospechoso o duplicado. Verifica en tu banco que corresponde a un ingreso distinto antes de aprobar.",
        "\n⚠️ This receipt is flagged as suspicious or duplicated. Verify in your bank that it represents a separate incoming payment before approving.",
        "\n⚠️ Este comprovante está marcado como suspeito ou duplicado. Verifique no banco se corresponde a um recebimento distinto antes de aprovar.",
    ),
    "ui_87c806ea25": (
        "Pulsa Crear mi bot y confirma la creación en Telegram. Después vuelve aquí a /start.",
        "Press Create my bot and confirm creation in Telegram. Then return here to /start.",
        "Pressione Criar meu bot e confirme a criação no Telegram. Depois volte aqui para /start.",
    ),
    "ui_87f86c9166": ("Paso 4/7 · Pagos", "Step 4/7 · Payments", "Etapa 4/7 · Pagamentos"),
    "ui_8806753ae0": (
        "Etiquetas separadas por comas (máximo 10). Coincide cualquiera de las etiquetas.",
        "Comma-separated tags (up to 10). Matches any of the tags.",
        "Etiquetas separadas por vírgulas (até 10). Corresponde a qualquer uma das etiquetas.",
    ),
    "ui_887df4dbba": (
        "\nSaldo: USD {p0:.2f}\nLa aprobación requiere verificar el ingreso real, no solo la imagen.",
        "\nBalance: USD {p0:.2f}\nApproval requires verifying the actual incoming payment, not only the image.",
        "\nSaldo: USD {p0:.2f}\nA aprovação exige verificar o recebimento real, não apenas a imagem.",
    ),
    "ui_888ea907df": (
        "🔎 Token recibido de forma privada. Estamos comprobando la identidad con Telegram.",
        "🔎 Token received privately. We are checking the identity with Telegram.",
        "🔎 Token recebido de forma privada. Estamos verificando a identidade com o Telegram.",
    ),
    "ui_88f77287cb": ("Duplicar", "Duplicate", "Duplicar"),
    "ui_89130f77b7": ("Desconectar", "Disconnect", "Desconectar"),
    "ui_894651580d": ("Activar / desactivar", "Enable / disable", "Ativar / desativar"),
    "ui_8a25c99c04": ("📣 Campañas", "📣 Campaigns", "📣 Campanhas"),
    "ui_8a5a57f162": ("Configurar instrucciones", "Configure instructions", "Configurar instruções"),
    "ui_8a6172e21a": ("Notas", "Notes", "Notas"),
    "ui_8a933e044a": ("Con suscripción activa", "With active subscription", "Com assinatura ativa"),
    "ui_8b0062fa48": ("Actualizado", "Updated", "Atualizado"),
    "ui_8b360bdff2": ("📣 Crear campaña", "📣 Create campaign", "📣 Criar campanha"),
    "ui_8b3fd404e4": ("Comprobante", "Receipt", "Comprovante"),
    "ui_8cbe82eda0": ("Sin configurar", "Not configured", "Não configurado"),
    "ui_8cc8c0ea28": (
        "{p0}\nReferencia: {p1}\nEstado: {p2}\nRecibido: {p3}",
        "{p0}\nReference: {p1}\nStatus: {p2}\nReceived: {p3}",
        "{p0}\nReferência: {p1}\nEstado: {p2}\nRecebido: {p3}",
    ),
    "ui_8cfe76a625": ("Notificaciones del negocio", "Business notifications", "Notificações do negócio"),
    "ui_8d1a37a8ad": ("Canal específico", "Specific channel", "Canal específico"),
    "ui_8e38c2571d": ("Activar", "Enable", "Ativar"),
    "ui_8ec04b2e9a": ("Usuarios seleccionados", "Selected users", "Usuários selecionados"),
    "ui_8f56865c5a": ("🔗 Botones", "🔗 Buttons", "🔗 Botões"),
    "ui_901226ffad": (
        "Suscripción mensual con renovación automática de Telegram. Revisa el importe antes de pagar.",
        "Monthly subscription with automatic Telegram renewal. Review the amount before paying.",
        "Assinatura mensal com renovação automática do Telegram. Confira o valor antes de pagar.",
    ),
    "ui_9087c1e5b9": (
        "Plan asociado a la invitación gratuita:",
        "Plan associated with the free invitation:",
        "Plano associado ao convite gratuito:",
    ),
    "ui_91673c23d9": (
        "Escribe la respuesta que recibirá el creador en este bot:",
        "Write the reply the creator will receive in this bot:",
        "Escreva a resposta que o criador receberá neste bot:",
    ),
    "ui_92485e58f8": ("🧾 Comprobantes", "🧾 Receipts", "🧾 Comprovantes"),
    "ui_92de7fea08": ("⬅️ Mi cuenta", "⬅️ My account", "⬅️ Minha conta"),
    "ui_939dbdae15": ("Confirmar envío", "Confirm send", "Confirmar envio"),
    "ui_93b2a9ef78": ("Fecha", "Date", "Data"),
    "ui_962cc91aa1": ("Paso 3/7 · Plan", "Step 3/7 · Plan", "Etapa 3/7 · Plano"),
    "ui_97431e865d": ("\nReferencia: ", "\nReference: ", "\nReferência: "),
    "ui_97532e8f6a": (
        "Importe del ajuste en USD (negativo para descuento), seguido del motivo. Ejemplo: -5 Descuento acordado",
        "Adjustment amount in USD (negative for a discount), followed by the reason. Example: -5 Agreed discount",
        "Valor do ajuste em USD (negativo para desconto), seguido do motivo. Exemplo: -5 Desconto acordado",
    ),
    "ui_97f305089c": (
        "💰 {p0}\n{p1} · {p2}\n{p3}",
        "💰 {p0}\n{p1} · {p2}\n{p3}",
        "💰 {p0}\n{p1} · {p2}\n{p3}",
    ),
    "ui_98e5acddb6": ("Estado", "Status", "Estado"),
    "ui_997dfc14fb": ("Orden", "Order", "Ordem"),
    "ui_9a1fd3962b": ("\nComisión: USD {p0:.2f}", "\nCommission: USD {p0:.2f}", "\nComissão: USD {p0:.2f}"),
    "ui_9a83846d18": (
        "Número de días y motivo. Ejemplo: 15 Cortesía acordada",
        "Number of days and reason. Example: 15 Agreed courtesy",
        "Número de dias e motivo. Exemplo: 15 Cortesia acordada",
    ),
    "ui_9ba422565b": ("Configuración inicial\n", "Initial setup\n", "Configuração inicial\n"),
    "ui_9c0fdb8e59": ("Resumen mensual", "Monthly summary", "Resumo mensal"),
    "ui_9c2d08cdfd": ("⚙️ Administrar mi bot", "⚙️ Manage my bot", "⚙️ Administrar meu bot"),
    "ui_9f093c955f": ("Tipo de producto", "Product type", "Tipo de produto"),
    "ui_9f3648bbb7": (
        "\nLa operación diaria se administra desde tu propio bot.",
        "\nDaily operations are managed from your own bot.",
        "\nAs operações diárias são administradas pelo seu próprio bot.",
    ),
    "ui_9f700d12b5": (
        "Envía el mensaje o un archivo con su pie de mensaje:",
        "Send the message or a file with its caption:",
        "Envie a mensagem ou um arquivo com sua legenda:",
    ),
    "ui_a02185f367": ("Revisar pago en Stars", "Review Stars payment", "Revisar pagamento em Stars"),
    "ui_a0bc738463": ("Mensaje de soporte", "Support message", "Mensagem de suporte"),
    "ui_a10168ba1c": ("Mes actual", "This month", "Mês atual"),
    "ui_a114da7782": ("Suscripción activa", "Active subscription", "Assinatura ativa"),
    "ui_a18123343e": ("Información adicional", "Additional information", "Informações adicionais"),
    "ui_a32d346b9b": ("{p0}: {p1} unidades mínimas", "{p0}: {p1} minor units", "{p0}: {p1} unidades mínimas"),
    "ui_a3b4f095b9": ("💰 Pagos", "💰 Payments", "💰 Pagamentos"),
    "ui_a3fb598cec": (
        "Etiquetas separadas por comas (máximo 10). Envía - para retirarlas.",
        "Comma-separated tags (up to 10). Send - to remove them.",
        "Etiquetas separadas por vírgulas (até 10). Envie - para removê-las.",
    ),
    "ui_a42b9bf9e9": ("\nHistorial:\n", "\nHistory:\n", "\nHistórico:\n"),
    "ui_a50715f097": ("Precio SaaS guardado.", "SaaS price saved.", "Preço SaaS salvo."),
    "ui_a576ce1586": (
        "Pago enviado para revisión. El saldo se actualizará cuando el administrador confirme el ingreso real.",
        "Payment submitted for review. The balance updates when the administrator confirms the actual incoming payment.",
        "Pagamento enviado para revisão. O saldo será atualizado quando o administrador confirmar o recebimento real.",
    ),
    "ui_a5b41aaecd": ("Suscripción SaaS", "SaaS subscription", "Assinatura SaaS"),
    "ui_a670af1bbd": (
        "Tasa guardada para ventas futuras. Las ventas anteriores conservan la suya. Puedes completar las facturas pendientes desde Facturas SaaS.",
        "Rate saved for future sales. Earlier sales keep their rate. You can complete pending invoices from SaaS invoices.",
        "Taxa salva para vendas futuras. As vendas anteriores mantêm a taxa original. Complete as faturas pendentes em Faturas SaaS.",
    ),
    "ui_a6fe6d4a43": ("Resumen diario", "Daily summary", "Resumo diário"),
    "ui_a8897541eb": ("💬 Conversaciones", "💬 Conversations", "💬 Conversas"),
    "ui_a89c6b90fb": ("Sin mensajes.", "No messages.", "Sem mensagens."),
    "ui_a9426ae3db": ("🎟 Membresías", "🎟 Memberships", "🎟 Assinaturas"),
    "ui_a94f745d4e": (
        ", referencia y motivo, separados por espacios. Ejemplo: 10 REF123 Devolución acordada",
        ", reference and reason, separated by spaces. Example: 10 REF123 Agreed refund",
        ", referência e motivo, separados por espaços. Exemplo: 10 REF123 Devolução acordada",
    ),
    "ui_aa81fd5fb3": (
        "Selecciona el método de pago de este precio.",
        "Select the payment method for this price.",
        "Selecione o método de pagamento deste preço.",
    ),
    "ui_aaaba064e3": ("Foto del bot", "Bot photo", "Foto do bot"),
    "ui_ab226e805f": ("Solicitar reembolso", "Request refund", "Solicitar reembolso"),
    "ui_ab434464d1": ("Tareas", "Tasks", "Tarefas"),
    "ui_ab559422f5": (
        "💳 Mi plan y facturación SaaS",
        "💳 My SaaS plan and billing",
        "💳 Meu plano e faturamento SaaS",
    ),
    "ui_abca487850": ("➕ Añadir o cambiar rol", "➕ Add or change role", "➕ Adicionar ou alterar função"),
    "ui_accbc07b1a": ("Abrir @", "Open @", "Abrir @"),
    "ui_ad43ae2f55": ("Resumen semanal", "Weekly summary", "Resumo semanal"),
    "ui_ad52fd2663": (
        "Indica el tipo real de producto. Los accesos a canales y contenido digital usan DIGITAL.",
        "Select the actual product type. Channel access and digital content use DIGITAL.",
        "Selecione o tipo real de produto. Acessos a canais e conteúdo digital usam DIGITAL.",
    ),
    "ui_adc6e09d37": ("Regalar días", "Gift days", "Presentear dias"),
    "ui_adc7700099": ("\nEventos: ", "\nEvents: ", "\nEventos: "),
    "ui_ae3e57808f": (
        "Añade el bot al canal como administrador con permisos para invitar y restringir miembros. Telegram avisará a la plataforma automáticamente.",
        "Add the bot to the channel as an administrator with permission to invite and restrict members. Telegram will notify the platform automatically.",
        "Adicione o bot ao canal como administrador com permissão para convidar e restringir membros. O Telegram notificará a plataforma automaticamente.",
    ),
    "ui_ae9c996e99": (
        "✅ Bot publicado y preparado para recibir clientes.",
        "✅ Bot published and ready to receive customers.",
        "✅ Bot publicado e pronto para receber clientes.",
    ),
    "ui_aef99d1b58": (
        "Preparando la vista previa y el recuento de destinatarios.",
        "Preparing the preview and recipient count.",
        "Preparando a prévia e a contagem de destinatários.",
    ),
    "ui_b06aabeb8e": ("💬 Soporte", "💬 Support", "💬 Suporte"),
    "ui_b093486b8e": ("Foto actualizada.", "Photo updated.", "Foto atualizada."),
    "ui_b0f6ff610e": (
        "Rol de este administrador:",
        "Role for this administrator:",
        "Função deste administrador:",
    ),
    "ui_b162ddab2e": ("Nombre del plan:", "Plan name:", "Nome do plano:"),
    "ui_b17e2d61f1": ("Nueva venta", "New sale", "Nova venda"),
    "ui_b1a584b2ea": (
        "Revisión de conexión en cola.",
        "Connection check queued.",
        "Verificação da conexão na fila.",
    ),
    "ui_b1e3e1d989": ("\n/cancel para salir.", "\n/cancel to exit.", "\n/cancel para sair."),
    "ui_b28640d7df": ("Abrir configuración", "Open settings", "Abrir configurações"),
    "ui_b29e0a896f": ("Fin del periodo", "Period end", "Fim do período"),
    "ui_b304de23d5": ("Sin ventas.", "No sales.", "Sem vendas."),
    "ui_b3b865b157": ("Imagen guardada", "Image saved", "Imagem salva"),
    "ui_b3d27ae7e5": (
        "Selecciona el canal incluido. El plan se cobrará en Telegram Stars.",
        "Select the included channel. The plan will be charged in Telegram Stars.",
        "Selecione o canal incluído. O plano será cobrado em Telegram Stars.",
    ),
    "ui_b3d92217ef": ("Historial de usos\n", "Usage history\n", "Histórico de usos\n"),
    "ui_b4063a14ee": (
        "¿Reembolsar {p0} {p1}? Esta acción devuelve el cobro y revoca el acceso si corresponde.",
        "Refund {p0} {p1}? This returns the charge and revokes access when applicable.",
        "Reembolsar {p0} {p1}? Esta ação devolve a cobrança e revoga o acesso quando aplicável.",
    ),
    "ui_b4ceef9a69": (
        "{p0}: USD {p1:g} + {p2:g}%",
        "{p0}: USD {p1:g} + {p2:g}%",
        "{p0}: USD {p1:g} + {p2:g}%",
    ),
    "ui_b618f50bd4": ("configurada", "configured", "configurada"),
    "ui_b662925851": ("pendiente", "pending", "pendente"),
    "ui_b7b48a33c0": ("Abrir mi bot", "Open my bot", "Abrir meu bot"),
    "ui_b7c2354b76": (
        "Otros mensajes automáticos",
        "Other automatic messages",
        "Outras mensagens automáticas",
    ),
    "ui_b8a21ed746": ("⬜ Desactivado", "⬜ Disabled", "⬜ Desativado"),
    "ui_b8ad035f75": ("Plan activado.", "Plan enabled.", "Plano ativado."),
    "ui_b9851c7113": (
        "Confirma el cambio de suscripción. No registra ningún cobro.",
        "Confirm the subscription change. This does not record a payment.",
        "Confirme a alteração da assinatura. Isso não registra um pagamento.",
    ),
    "ui_ba4270a01a": (
        "soporte, términos, privacidad y reembolsos",
        "support, terms, privacy and refunds",
        "suporte, termos, privacidade e reembolsos",
    ),
    "ui_bb16b73fa6": ("Últimos 7 días", "Last 7 days", "Últimos 7 dias"),
    "ui_bb5151dfcc": (
        "Confirma la decisión sobre este pago:",
        "Confirm the decision about this payment:",
        "Confirme a decisão sobre este pagamento:",
    ),
    "ui_bb7b58a4ab": (
        "IDs numéricos separados por comas (máximo 1000):",
        "Comma-separated numeric IDs (up to 1000):",
        "IDs numéricos separados por vírgulas (até 1000):",
    ),
    "ui_bb7bb4a0e8": (
        "\nAjustes/descuentos: USD {p0:.2f}\nPagado: USD {p1:.2f}\nSaldo: USD {p2:.2f}\nVence: {p3}",
        "\nAdjustments/discounts: USD {p0:.2f}\nPaid: USD {p1:.2f}\nBalance: USD {p2:.2f}\nDue: {p3}",
        "\nAjustes/descontos: USD {p0:.2f}\nPago: USD {p1:.2f}\nSaldo: USD {p2:.2f}\nVence: {p3}",
    ),
    "ui_bb9dbb406d": ("Cancelar", "Cancel", "Cancelar"),
    "ui_bc5ae47b3c": ("\n{p0}\n@{p1} · {p2}\n", "\n{p0}\n@{p1} · {p2}\n", "\n{p0}\n@{p1} · {p2}\n"),
    "ui_bd02b9a7d7": ("Todos", "All", "Todos"),
    "ui_bd1f309cd6": ("Falta completar:\n", "Still required:\n", "Falta completar:\n"),
    "ui_bd59ce9793": (
        "🏢 {p0}\nPlan: {p1}\nEstado: {p2}",
        "🏢 {p0}\nPlan: {p1}\nStatus: {p2}",
        "🏢 {p0}\nPlano: {p1}\nEstado: {p2}",
    ),
    "ui_be141d718a": ("Cambiar plan", "Change plan", "Alterar plano"),
    "ui_be8d017030": (
        "📢 {p0}\n{p1}\nAudiencia: {p2}\nTotal: {p3}\nEnviados: {p4}\nFallidos: {p5}\nBloqueados: {p6}\nEntrega incierta: {p7}\n\n{p8}",
        "📢 {p0}\n{p1}\nAudience: {p2}\nTotal: {p3}\nSent: {p4}\nFailed: {p5}\nBlocked: {p6}\nDelivery uncertain: {p7}\n\n{p8}",
        "📢 {p0}\n{p1}\nPúblico: {p2}\nTotal: {p3}\nEnviados: {p4}\nFalhas: {p5}\nBloqueados: {p6}\nEntrega incerta: {p7}\n\n{p8}",
    ),
    "ui_be9374267e": ("Mensajes predeterminados", "Default messages", "Mensagens padrão"),
    "ui_bee802da1b": ("❌ Rechazar", "❌ Reject", "❌ Rejeitar"),
    "ui_bef082568b": (
        "📄 {p0}\nEstado: {p1}\nCuota: USD {p2:.2f}",
        "📄 {p0}\nStatus: {p1}\nFixed fee: USD {p2:.2f}",
        "📄 {p0}\nEstado: {p1}\nTaxa fixa: USD {p2:.2f}",
    ),
    "ui_bf25dd557c": (
        "✅ Guardado. La configuración se sincronizará con Telegram.",
        "✅ Saved. The settings will sync with Telegram.",
        "✅ Salvo. A configuração será sincronizada com o Telegram.",
    ),
    "ui_c203da909d": ("Referidos", "Referrals", "Indicações"),
    "ui_c25cdfcf7e": (
        "Envía texto o una imagen, vídeo o documento con su pie de mensaje. Con archivos, el texto admite hasta 1024 caracteres.",
        "Send text or an image, video or document with a caption. File captions allow up to 1024 characters.",
        "Envie texto ou uma imagem, vídeo ou documento com legenda. As legendas de arquivos permitem até 1024 caracteres.",
    ),
    "ui_c282199b2b": ("Por plan", "By plan", "Por plano"),
    "ui_c2866fe464": ("Por invitación", "From invitation", "Por convite"),
    "ui_c3d3bde02a": ("Nombre de tu nuevo plan:", "Name of your new plan:", "Nome do seu novo plano:"),
    "ui_c3eb9ca000": ("Banco", "Bank", "Banco"),
    "ui_c43c3b68b2": (
        "Estado del negocio actualizado.",
        "Business status updated.",
        "Estado do negócio atualizado.",
    ),
    "ui_c6511757a1": ("\nSelecciona un registro:", "\nSelect a record:", "\nSelecione um registro:"),
    "ui_c654c831c3": ("Selecciona la audiencia:", "Select the audience:", "Selecione o público:"),
    "ui_c66894eaff": ("Ver imagen", "View attachment", "Ver anexo"),
    "ui_c6d042cc22": ("🔑 Reemplazar token / bot", "🔑 Replace token / bot", "🔑 Substituir token / bot"),
    "ui_c7882bd0a9": (
        "Envía el token de tu bot generado por @BotFather. Lo validaremos y te mostraremos su identidad antes de conectarlo. Se guardará cifrado y trataremos de eliminar este mensaje del chat.",
        "Send your bot token generated by @BotFather. We will validate it and show its identity before connecting it. It will be stored encrypted and we will try to remove this message from the chat.",
        "Envie o token do seu bot gerado por @BotFather. Vamos validá-lo e mostrar sua identidade antes de conectá-lo. Ele será armazenado criptografado e tentaremos remover esta mensagem do chat.",
    ),
    "ui_c82f472089": ("Marcar sospechoso", "Mark suspicious", "Marcar como suspeito"),
    "ui_c8f7c87d4b": ("💳 Planes SaaS", "💳 SaaS plans", "💳 Planos SaaS"),
    "ui_c932d29a53": ("⏱ Automatizaciones", "⏱ Automations", "⏱ Automações"),
    "ui_cb62dc4b5e": ("Facturas SaaS", "SaaS invoices", "Faturas SaaS"),
    "ui_cbf28b1516": ("Cuenta / IBAN", "Account / IBAN", "Conta / IBAN"),
    "ui_cc24326e48": ("❓ Ayuda y soporte", "❓ Help and support", "❓ Ajuda e suporte"),
    "ui_cd20eb864b": ("Canal con permisos", "Channel permissions", "Permissões do canal"),
    "ui_cd25ee5b1d": ("Pausar", "Pause", "Pausar"),
    "ui_cd3f4d9ab5": (
        "{p0} @{p1}\nTelegram ID: {p2}\n{p3} · {p4}\nOrigen: {p5}\nInicio: {p6}\nFin: {p7}\nDías restantes: {p8}",
        "{p0} @{p1}\nTelegram ID: {p2}\n{p3} · {p4}\nOrigin: {p5}\nStart: {p6}\nEnd: {p7}\nDays remaining: {p8}",
        "{p0} @{p1}\nID Telegram: {p2}\n{p3} · {p4}\nOrigem: {p5}\nInício: {p6}\nFim: {p7}\nDias restantes: {p8}",
    ),
    "ui_cd6fc18cba": ("🔑 Conectar mi bot", "🔑 Connect my bot", "🔑 Conectar meu bot"),
    "ui_ce2ae67021": ("📋 Actividad", "📋 Activity", "📋 Atividade"),
    "ui_ce8e3b6256": ("Funciones", "Features", "Funções"),
    "ui_cf2563451a": ("Moneda del precio:", "Price currency:", "Moeda do preço:"),
    "ui_d0233d6a24": (
        "Nombre, descripción, soporte y políticas",
        "Name, description, support and policies",
        "Nome, descrição, suporte e políticas",
    ),
    "ui_d0ec90ce99": (
        "Escribe una nota interna (máximo 2000 caracteres):",
        "Write an internal note (up to 2000 characters):",
        "Escreva uma nota interna (até 2000 caracteres):",
    ),
    "ui_d1bbd1ed38": ("Instrucciones", "Instructions", "Instruções"),
    "ui_d1bcbd69dc": ("Historial:", "History:", "Histórico:"),
    "ui_d21d088519": (
        " mediante el proveedor de pago. Confirma para solicitar la devolución real.",
        " through the payment provider. Confirm to request the actual refund.",
        " pelo provedor de pagamento. Confirme para solicitar a devolução real.",
    ),
    "ui_d22dcf2e9b": ("Por vencer", "Expiring soon", "Próximas do vencimento"),
    "ui_d2af31712e": ("Mensaje", "Message", "Mensagem"),
    "ui_d2fdf1c25d": ("Mostrar / ocultar", "Show / hide", "Mostrar / ocultar"),
    "ui_d30cf0cfea": ("Filtrar registros", "Filter records", "Filtrar registros"),
    "ui_d32ea0ea3e": ("Nuevo usuario", "New user", "Novo usuário"),
    "ui_d343e701b4": (
        "📊 Últimos 30 días\nClientes: {p0}\nNuevos: {p1}\nMembresías activas: {p2}\nComprobantes pendientes: {p3}\nConversión: {p4}%\nIngresos (unidades mínimas por moneda): {p5}",
        "📊 Last 30 days\nCustomers: {p0}\nNew: {p1}\nActive memberships: {p2}\nPending receipts: {p3}\nConversion: {p4}%\nRevenue (minor units by currency): {p5}",
        "📊 Últimos 30 dias\nClientes: {p0}\nNovos: {p1}\nAssinaturas ativas: {p2}\nComprovantes pendentes: {p3}\nConversão: {p4}%\nReceita (unidades mínimas por moeda): {p5}",
    ),
    "ui_d4a256c2db": ("Descripción corta", "Short description", "Descrição curta"),
    "ui_d50da7400c": (
        "Cambio administrativo de plan",
        "Administrative plan change",
        "Alteração administrativa de plano",
    ),
    "ui_d51ddf5f9d": (
        "{p0} @{p1}\nRol: {p2}\nPermisos: {p3}",
        "{p0} @{p1}\nRole: {p2}\nPermissions: {p3}",
        "{p0} @{p1}\nFunção: {p2}\nPermissões: {p3}",
    ),
    "ui_d5a804455b": ("Duración", "Duration", "Duração"),
    "ui_d5d63bad38": ("Se devolverán ", "The refund amount is ", "Serão devolvidos "),
    "ui_d6919eba9d": ("Moneda", "Currency", "Moeda"),
    "ui_d73d157040": ("Planes del bot", "Bot plans", "Planos do bot"),
    "ui_d8171a3c63": ("Bot conectado", "Bot connected", "Bot conectado"),
    "ui_da1254a91b": ("\nGasto confirmado: ", "\nConfirmed spending: ", "\nGasto confirmado: "),
    "ui_dbae0b2a1a": ("Prioridad", "Priority", "Prioridade"),
    "ui_dc30db150a": ("🎁 Conceder acceso gratuito", "🎁 Grant free access", "🎁 Conceder acesso gratuito"),
    "ui_dc5df7685c": (
        "Fecha inicial y final (inclusive), formato AAAA-MM-DD AAAA-MM-DD:",
        "Start and end dates (inclusive), format YYYY-MM-DD YYYY-MM-DD:",
        "Datas inicial e final (inclusive), formato AAAA-MM-DD AAAA-MM-DD:",
    ),
    "ui_dc87d8b50f": (
        "🤖 @{p0}\nID: {p1}\nEstado: {p2}\nLa configuración y los clientes están en tu propio bot.",
        "🤖 @{p0}\nID: {p1}\nStatus: {p2}\nManage settings and customers from your own bot.",
        "🤖 @{p0}\nID: {p1}\nEstado: {p2}\nAs configurações e os clientes estão no seu próprio bot.",
    ),
    "ui_dcdac0bd75": ("⭐ Planes y precios", "⭐ Plans and prices", "⭐ Planos e preços"),
    "ui_de5196ff47": (
        "✅ Instrucciones de cobro guardadas.",
        "✅ Payment instructions saved.",
        "✅ Instruções de pagamento salvas.",
    ),
    "ui_dea8511fd8": (
        "Revisión guardada. El cliente recibirá una notificación.",
        "Review saved. The customer will receive a notification.",
        "Revisão salva. O cliente receberá uma notificação.",
    ),
    "ui_dee82cc957": (
        "\nAbre el nuevo Master en @BotFather y activa Bot Management Mode.",
        "\nOpen the new master bot in @BotFather and enable Bot Management Mode.",
        "\nAbra o novo bot principal em @BotFather e ative Bot Management Mode.",
    ),
    "ui_df139d8928": ("Registrar devolución bancaria", "Record bank refund", "Registrar devolução bancária"),
    "ui_dfee336770": ("Idiomas", "Languages", "Idiomas"),
    "ui_e0161a4c98": (
        "💳 Finanzas de MI plataforma\nCobrado: USD {p0:.2f}\nFacturas pendientes: {p1}",
        "💳 MY platform finances\nCollected: USD {p0:.2f}\nPending invoices: {p1}",
        "💳 Finanças da MINHA plataforma\nRecebido: USD {p0:.2f}\nFaturas pendentes: {p1}",
    ),
    "ui_e0757e6bc4": (
        "Realiza primero la devolución en tu banco. Envía importe en ",
        "First complete the refund in your bank. Send the amount in ",
        "Primeiro realize a devolução no banco. Envie o valor em ",
    ),
    "ui_e0e251a172": ("Webhook ID", "Webhook ID", "ID do webhook"),
    "ui_e125d78231": ("📺 Canales incluidos", "📺 Included channels", "📺 Canais incluídos"),
    "ui_e2a573d70b": (
        "Nombre interno de la difusión:",
        "Internal broadcast name:",
        "Nome interno da transmissão:",
    ),
    "ui_e2ea3a9315": ("Cambio programado para ", "Change scheduled for ", "Alteração agendada para "),
    "ui_e38033fedf": ("🎁 Pruebas activas", "🎁 Active trials", "🎁 Testes ativos"),
    "ui_e38de60f7d": ("Confirmar cancelación", "Confirm cancellation", "Confirmar cancelamento"),
    "ui_e4dcc603e1": ("\nDevoluciones:\n", "\nRefunds:\n", "\nReembolsos:\n"),
    "ui_e5003d1479": (
        "Campaña en cola. Puedes consultar su avance y pausarla desde Campañas.",
        "Campaign queued. You can view progress and pause it from Campaigns.",
        "Campanha na fila. Consulte o progresso e pause em Campanhas.",
    ),
    "ui_e520b01b67": ("🛡 Administrar plataforma", "🛡 Manage platform", "🛡 Administrar plataforma"),
    "ui_e586de2fbc": ("✅ Crear invitación", "✅ Create invitation", "✅ Criar convite"),
    "ui_e5ce07356d": ("{p0}: {p1} ⭐/30 días", "{p0}: {p1} ⭐/30 days", "{p0}: {p1} ⭐/30 dias"),
    "ui_e63521cd74": (
        "Reporte {p0}\nEstado: {p1}",
        "Report {p0}\nStatus: {p1}",
        "Relatório {p0}\nEstado: {p1}",
    ),
    "ui_e6bbd34190": (
        "⚙️ Nombre, textos y políticas",
        "⚙️ Name, messages and policies",
        "⚙️ Nome, mensagens e políticas",
    ),
    "ui_e746643f44": ("Proveedor", "Provider", "Provedor"),
    "ui_e80081e7a4": ("Recordatorio de vencimiento", "Expiry reminder", "Lembrete de vencimento"),
    "ui_e9381004a1": (
        "Selecciona tu negocio o crea uno para conectar tu bot.",
        "Select your business or create one to connect your bot.",
        "Selecione seu negócio ou crie um para conectar seu bot.",
    ),
    "ui_e9d7121d24": ("🔎 Filtros y búsqueda", "🔎 Filters and search", "🔎 Filtros e busca"),
    "ui_ea0a97f6e5": (
        "✅ Conexión confirmada. Estamos configurando tu bot.",
        "✅ Connection confirmed. We are setting up your bot.",
        "✅ Conexão confirmada. Estamos configurando seu bot.",
    ),
    "ui_ea53e76c4a": ("👥 Usuarios", "👥 Users", "👥 Usuários"),
    "ui_eaca0caa4f": (
        "Envía ID numérico y rol separados por un espacio.\nRoles: SUPERVISOR, PAYMENTS, SALES, SUPPORT, READ_ONLY.\nEjemplo: 123456789 SUPPORT\nLa persona debe haber abierto antes este bot maestro.",
        "Send the numeric ID and role separated by a space.\nRoles: SUPERVISOR, PAYMENTS, SALES, SUPPORT, READ_ONLY.\nExample: 123456789 SUPPORT\nThe person must have started this master bot first.",
        "Envie o ID numérico e a função separados por um espaço.\nFunções: SUPERVISOR, PAYMENTS, SALES, SUPPORT, READ_ONLY.\nExemplo: 123456789 SUPPORT\nA pessoa deve ter iniciado este bot principal antes.",
    ),
    "ui_eb02ca78d4": ("👁 Vista previa y confirmar", "👁 Preview and confirm", "👁 Prévia e confirmação"),
    "ui_ec306f70d8": (
        "Comprobación solicitada. Solo una confirmación válida del proveedor registrará el cobro.",
        "Verification requested. Only a valid provider confirmation will record a payment.",
        "Verificação solicitada. Somente uma confirmação válida do provedor registrará o pagamento.",
    ),
    "ui_ec42386dd7": (
        "Nuevo valor de {p0}. Beneficios: uno por línea.",
        "New value for {p0}. Benefits: one per line.",
        "Novo valor de {p0}. Benefícios: um por linha.",
    ),
    "ui_ee00b96fff": ("Descripción", "Description", "Descrição"),
    "ui_ee2bc96713": ("Reportes anteriores", "Previous reports", "Relatórios anteriores"),
    "ui_ee6b79c573": ("\nSin registros.", "\nNo records.", "\nNenhum registro."),
    "ui_eea6aee201": ("Actualizar progreso", "Refresh progress", "Atualizar progresso"),
    "ui_ef02fbd26e": ("Mensaje después de comprar", "Message after purchase", "Mensagem após a compra"),
    "ui_ef40057b06": (
        "1. Crea tu cuenta y activa la prueba de 3 días.\n2. Abre @BotFather y crea tu bot con /newbot.\n3. Vuelve aquí, pulsa Conectar mi bot y envía el token.\n4. Confirma el nombre y usuario que devuelve Telegram.\n5. Abre TU bot y sigue Configuración inicial.\nTu cuenta SaaS, facturas y conexión se administran aquí. Tu negocio se administra en tu bot.",
        "1. Create your account and start the 3-day trial.\n2. Open @BotFather and create your bot with /newbot.\n3. Return here, press Connect my bot and send the token.\n4. Confirm the name and username returned by Telegram.\n5. Open YOUR bot and follow Initial setup.\nManage your SaaS account, invoices and connection here. Manage your business in your bot.",
        "1. Crie sua conta e inicie o teste de 3 dias.\n2. Abra @BotFather e crie seu bot com /newbot.\n3. Volte aqui, pressione Conectar meu bot e envie o token.\n4. Confirme o nome e usuário retornados pelo Telegram.\n5. Abra SEU bot e siga Configuração inicial.\nSua conta SaaS, faturas e conexão são administradas aqui. Seu negócio é administrado no seu bot.",
    ),
    "ui_efdf4a8868": ("Precios", "Prices", "Preços"),
    "ui_eff4701a31": (
        "Reembolso solicitado. El historial se actualizará al recibir la confirmación del proveedor.",
        "Refund requested. History will update when the provider confirms it.",
        "Reembolso solicitado. O histórico será atualizado quando o provedor confirmar.",
    ),
    "ui_f183215e53": (
        "Plan desactivado. Las membresías existentes se conservan.",
        "Plan disabled. Existing memberships are preserved.",
        "Plano desativado. As assinaturas existentes são mantidas.",
    ),
    "ui_f18f127b2f": ("❓ Ayuda de conexión", "❓ Connection help", "❓ Ajuda de conexão"),
    "ui_f1a5125bb4": ("Enlaces", "Links", "Links"),
    "ui_f2397b8403": (
        "Moneda y valor en centavos USD de una unidad mínima de esa moneda. Ejemplo: MXN 0.055 (un centavo MXN). Para XTR, la unidad es una Star. Usa una tasa acordada y documentada, no una estimación arbitraria.",
        "Currency and USD cents per minor unit of that currency. Example: MXN 0.055 (one MXN cent). For XTR, the unit is one Star. Use an agreed, documented rate, not an arbitrary estimate.",
        "Moeda e centavos USD por unidade mínima dessa moeda. Exemplo: MXN 0.055 (um centavo MXN). Para XTR, a unidade é uma Star. Use uma taxa acordada e documentada, não uma estimativa arbitrária.",
    ),
    "ui_f2752fb04c": ("🏦 Transferencia", "🏦 Bank transfer", "🏦 Transferência bancária"),
    "ui_f35f9141f4": ("Archivar", "Archive", "Arquivar"),
    "ui_f366f3f9d4": ("conexión de Telegram", "Telegram connection", "conexão do Telegram"),
    "ui_f45745c7a1": ("Registros del negocio", "Business records", "Registros do negócio"),
    "ui_f47a99ebcf": ("Secret key", "Secret key", "Chave secreta"),
    "ui_f55e0ec28b": ("Sin canal (membresía)", "No channel (membership)", "Sem canal (assinatura)"),
    "ui_f5f273d88e": ("Bienvenida", "Welcome", "Boas-vindas"),
    "ui_f7d88a8e20": ("📝 Nota interna", "📝 Internal note", "📝 Nota interna"),
    "ui_f7f9fa14b0": (
        "Días de tolerancia después de emitir la factura (0 a 30). Afecta a ciclos nuevos:",
        "Grace days after an invoice is issued (0 to 30). Applies to new cycles:",
        "Dias de tolerância após emitir a fatura (0 a 30). Aplica-se a ciclos novos:",
    ),
    "ui_f851d9a83a": ("Cliente", "Customer", "Cliente"),
    "ui_f8ed7dc055": (
        "Configura tu negocio desde este bot. Usa Configuración inicial para conectar canales, crear planes, elegir pagos y publicar.\nMi cuenta SaaS en el bot maestro muestra tu prueba, plan y facturas.\nLos botones siempre vuelven a Inicio; /cancel abandona un formulario.",
        "Manage your business from this bot. Use Initial setup to connect channels, create plans, choose payment methods and publish.\nMy SaaS account in the master bot shows your trial, plan and invoices.\nUse Home to return to the menu; /cancel exits a form.",
        "Administre seu negócio neste bot. Use Configuração inicial para conectar canais, criar planos, escolher pagamentos e publicar.\nMinha conta SaaS no bot principal mostra seu teste, plano e faturas.\nUse Início para voltar ao menu; /cancel sai de um formulário.",
    ),
    "ui_f944c163de": ("Extender", "Extend", "Estender"),
    "ui_fad8976f20": ("Precio: {p0} Stars", "Price: {p0} Stars", "Preço: {p0} Stars"),
    "ui_fb02cd914b": ("Cancelación", "Cancellation", "Cancelamento"),
    "ui_fb9f51fe92": ("Rol", "Role", "Função"),
    "ui_fcb17cdb35": (
        "\nIngresos del ciclo por moneda:\n",
        "\nCycle revenue by currency:\n",
        "\nReceita do ciclo por moeda:\n",
    ),
    "ui_fd393ff98d": ("Verificar canales", "Verify channels", "Verificar canais"),
    "ui_fddd00f8fc": (
        "1. Crea tu negocio y su bot con el botón oficial de Telegram.\n2. Configura textos, soporte y políticas.\n3. Conecta el canal y crea un plan en Stars.\n4. Abre el bot hijo, pulsa Iniciar y vuelve aquí para publicarlo.\nUsa /support para contactar con la plataforma.\nNunca necesitas enviarnos el token de un bot hijo.",
        "1. Create your business and its bot with Telegram's official button.\n2. Set up messages, support and policies.\n3. Connect the channel and create a Stars plan.\n4. Open the child bot, press Start and return here to publish it.\nUse /support to contact the platform.\nThis managed-bot route does not require you to send a child bot token.",
        "1. Crie seu negócio e seu bot com o botão oficial do Telegram.\n2. Configure mensagens, suporte e políticas.\n3. Conecte o canal e crie um plano em Stars.\n4. Abra o bot conectado, pressione Iniciar e volte aqui para publicá-lo.\nUse /support para entrar em contato com a plataforma.\nEsta opção de bot gerenciado não exige o envio do token do bot conectado.",
    ),
    "ui_fe09335615": ("✅ Confirmar cambio", "✅ Confirm change", "✅ Confirmar alteração"),
    "ui_fe18c98897": ("🏦 Transferencia: ", "🏦 Bank transfer: ", "🏦 Transferência: "),
    "ui_fe24c9a8f7": (
        "Cancelar renovación de plataforma",
        "Cancel platform renewal",
        "Cancelar renovação da plataforma",
    ),
    "ui_fe2ba13be4": (
        "\nActivo: {p0}\nVisible: {p1}\nArchivado: {p2}\nRenovación automática: {p3}\nCanales: {p4}",
        "\nActive: {p0}\nVisible: {p1}\nArchived: {p2}\nAutomatic renewal: {p3}\nChannels: {p4}",
        "\nAtivo: {p0}\nVisível: {p1}\nArquivado: {p2}\nRenovação automática: {p3}\nCanais: {p4}",
    ),
}
