"""Initial central tenant schema"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_users",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("telegram_user_id"),
    )
    with op.batch_alter_table("platform_users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_platform_users_created_at"), ["created_at"], unique=False)

    op.create_table(
        "saas_plans",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("limits", sa.JSON(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("prices", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("saas_plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saas_plans_created_at"), ["created_at"], unique=False)

    op.create_table(
        "auth_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("bot_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_auth_sessions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_auth_sessions_expires_at"), ["expires_at"], unique=False)

    op.create_table(
        "platform_support_tickets",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subject", sa.String(length=120), nullable=False),
        sa.Column("text", sa.String(length=3000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("platform_support_tickets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_platform_support_tickets_created_at"), ["created_at"], unique=False
        )

    op.create_table(
        "tenants",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("suspended_at", sa.BigInteger(), nullable=True),
        sa.Column("deleted_at", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenants_created_at"), ["created_at"], unique=False)

    op.create_table(
        "audit_logs",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bot_creation_requests",
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("request_id", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("consumed_bot_id", sa.String(length=36), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("bot_creation_requests", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bot_creation_requests_created_at"), ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_bot_creation_requests_telegram_user_id"), ["telegram_user_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_bot_creation_requests_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "coupons",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("percent_off", sa.Integer(), nullable=False),
        sa.Column("max_redemptions", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "code"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("coupons", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_coupons_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_coupons_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "events",
        sa.Column("bot_id", sa.String(length=36), nullable=True),
        sa.Column("contact_id", sa.String(length=36), nullable=True),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("dedup_key", sa.String(length=180), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "dedup_key"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_type"), ["type"], unique=False)

    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "key"),
    )
    with op.batch_alter_table("feature_flags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feature_flags_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_feature_flags_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("bot_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("dedup_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("run_at", sa.BigInteger(), nullable=False),
        sa.Column("lease_until", sa.BigInteger(), nullable=True),
        sa.Column("lease_owner", sa.String(length=36), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error_code", sa.String(length=80), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedup_key"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index("ix_job_due", ["status", "run_at", "tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_jobs_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "managed_bots",
        sa.Column("telegram_bot_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("public_id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("config_version", sa.Integer(), nullable=False),
        sa.Column("last_update_at", sa.BigInteger(), nullable=True),
        sa.Column("health", sa.JSON(), nullable=False),
        sa.Column("last_error_code", sa.String(length=60), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("public_id"),
        sa.UniqueConstraint("telegram_bot_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("managed_bots", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_managed_bots_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_managed_bots_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "onboarding",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("step", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "user_id"),
    )
    with op.batch_alter_table("onboarding", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_onboarding_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_onboarding_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "payment_provider_configs",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("approved_for_activity", sa.Boolean(), nullable=False),
        sa.Column("public_config", sa.JSON(), nullable=False),
        sa.Column("secrets_ciphertext", sa.JSON(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "provider"),
    )
    with op.batch_alter_table("payment_provider_configs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payment_provider_configs_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payment_provider_configs_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "provider_events",
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("account_key", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "account_key", "external_id"),
    )
    with op.batch_alter_table("provider_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_provider_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_provider_events_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "saas_invoices",
        sa.Column("invoice_payload", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_xtr", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("checkout_url", sa.String(length=1024), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["saas_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_payload"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("saas_invoices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saas_invoices_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_saas_invoices_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "saas_subscriptions",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("trial_ends_at", sa.BigInteger(), nullable=False),
        sa.Column("current_period_end", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["saas_plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("saas_subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saas_subscriptions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_saas_subscriptions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "name"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tags_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "telegram_updates",
        sa.Column("bot_key", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=True),
        sa.Column("update_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_key", "update_id"),
    )
    with op.batch_alter_table("telegram_updates", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_telegram_updates_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_telegram_updates_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "tenant_members",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "user_id"),
    )
    with op.batch_alter_table("tenant_members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tenant_members_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenant_members_tenant_id"), ["tenant_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tenant_members_user_id"), ["user_id"], unique=False)

    op.create_table(
        "usage_counters",
        sa.Column("key", sa.String(length=60), nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("value", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "key", "period"),
    )
    with op.batch_alter_table("usage_counters", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_usage_counters_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_usage_counters_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "automation_rules",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("trigger", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("delay_seconds", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("automation_rules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_automation_rules_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_automation_rules_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bot_secrets",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("token_ciphertext", sa.JSON(), nullable=False),
        sa.Column("webhook_ciphertext", sa.JSON(), nullable=False),
        sa.Column("webhook_secret_hash", sa.String(length=64), nullable=False),
        sa.Column("token_version", sa.Integer(), nullable=False),
        sa.Column("token_last_rotated_at", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("bot_secrets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bot_secrets_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bot_secrets_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bot_settings",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("short_description", sa.String(length=120), nullable=False),
        sa.Column("menu_text", sa.String(length=32), nullable=False),
        sa.Column("commands", sa.JSON(), nullable=False),
        sa.Column("branding", sa.JSON(), nullable=False),
        sa.Column("policies", sa.JSON(), nullable=False),
        sa.Column("template", sa.String(length=40), nullable=False),
        sa.Column("support_username", sa.String(length=64), nullable=False),
        sa.Column("remove_expired_members", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("bot_settings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bot_settings_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bot_settings_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bot_texts",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("locale", sa.String(length=8), nullable=False),
        sa.Column("value", sa.String(length=4096), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "key", "locale"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("bot_texts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bot_texts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bot_texts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "campaigns",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("segment", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scheduled_at", sa.BigInteger(), nullable=True),
        sa.Column("cursor", sa.String(length=36), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaigns_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaigns_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "channels",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("permissions", sa.JSON(), nullable=False),
        sa.Column("connected_at", sa.BigInteger(), nullable=True),
        sa.Column("access_mode", sa.String(length=30), nullable=False),
        sa.Column("native_invite_link", sa.String(length=512), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "telegram_chat_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_channels_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_channels_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "contacts",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=True),
        sa.Column("campaign", sa.String(length=64), nullable=True),
        sa.Column("referrer", sa.String(length=36), nullable=True),
        sa.Column("last_seen_at", sa.BigInteger(), nullable=False),
        sa.Column("opted_out", sa.Boolean(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "telegram_user_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contacts_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_stage"), ["stage"], unique=False)
        batch_op.create_index(batch_op.f("ix_contacts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "saas_charges",
        sa.Column("charge_id", sa.String(length=255), nullable=False),
        sa.Column("invoice_id", sa.String(length=36), nullable=False),
        sa.Column("amount_xtr", sa.BigInteger(), nullable=False),
        sa.Column("period_end", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["saas_invoices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("charge_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("saas_charges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_saas_charges_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_saas_charges_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "attribution_links",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("campaign", sa.String(length=64), nullable=True),
        sa.Column("referrer_id", sa.String(length=36), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "referrer_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("attribution_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_attribution_links_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_attribution_links_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "automation_executions",
        sa.Column("rule_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "event_id"],
            ["events.tenant_id", "events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "rule_id"],
            ["automation_rules.tenant_id", "automation_rules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "event_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("automation_executions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_automation_executions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_automation_executions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "campaign_recipients",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "campaign_id"],
            ["campaigns.tenant_id", "campaigns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "contact_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("campaign_recipients", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_campaign_recipients_campaign_id"), ["campaign_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaign_recipients_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_campaign_recipients_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "contact_tags",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("tag_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "tag_id"],
            ["tags.tenant_id", "tags.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_id", "tag_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("contact_tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contact_tags_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_contact_tags_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("contact_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_conversations_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_conversations_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "crm_tasks",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("crm_tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_crm_tasks_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_crm_tasks_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "internal_notes",
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("author_id", sa.String(length=36), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("internal_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_internal_notes_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_internal_notes_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "plans",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("channel_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("benefits", sa.JSON(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("product_kind", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("duration_days > 0"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["channels.tenant_id", "channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plans_bot_id"), ["bot_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_plans_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_plans_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "referrals",
        sa.Column("referrer_id", sa.String(length=36), nullable=False),
        sa.Column("referred_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reward_units", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "referred_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "referrer_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referred_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("referrals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_referrals_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_referrals_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("admin_id", sa.String(length=36), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "conversation_id"],
            ["conversations.tenant_id", "conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_conversation_id"), ["conversation_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_messages_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "payments",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("recurring", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("invoice_payload", sa.String(length=128), nullable=False),
        sa.Column("checkout_url", sa.String(length=1024), nullable=True),
        sa.Column("confirmed_at", sa.BigInteger(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount_minor > 0"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "plan_id"],
            ["plans.tenant_id", "plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_payload"),
        sa.UniqueConstraint("tenant_id", "id"),
        sa.UniqueConstraint("tenant_id", "idempotency_key"),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payments_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_payments_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_payments_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_payments_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "plan_prices",
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.CheckConstraint("amount_minor > 0"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "plan_id"],
            ["plans.tenant_id", "plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("plan_id", "provider", "currency"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("plan_prices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_plan_prices_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_plan_prices_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "bank_receipts",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("perceptual_hash", sa.String(length=16), nullable=True),
        sa.Column("storage_key", sa.String(length=120), nullable=False),
        sa.Column("media_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("suspicious", sa.Boolean(), nullable=False),
        sa.Column("duplicate", sa.Boolean(), nullable=False),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("review_note", sa.String(length=500), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "payment_id"],
            ["payments.tenant_id", "payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("bank_receipts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_bank_receipts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_receipts_payment_id"), ["payment_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_receipts_sha256"), ["sha256"], unique=False)
        batch_op.create_index(batch_op.f("ix_bank_receipts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "coupon_redemptions",
        sa.Column("coupon_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "coupon_id"],
            ["coupons.tenant_id", "coupons.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "payment_id"],
            ["payments.tenant_id", "payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("coupon_id", "contact_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("coupon_redemptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_coupon_redemptions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_coupon_redemptions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "payment_attempts",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "payment_id"],
            ["payments.tenant_id", "payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("payment_attempts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_attempts_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_attempts_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "payment_charges",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("charge_id", sa.String(length=255), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=8), nullable=False),
        sa.Column("period_end", sa.BigInteger(), nullable=True),
        sa.Column("refunded_at", sa.BigInteger(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "payment_id"],
            ["payments.tenant_id", "payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_id", "provider", "charge_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("payment_charges", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payment_charges_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_payment_charges_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("bot_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("plan_id", sa.String(length=36), nullable=False),
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("starts_at", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("auto_renew", sa.Boolean(), nullable=False),
        sa.Column("initial_charge_id", sa.String(length=255), nullable=True),
        sa.Column("renewal_status", sa.String(length=20), nullable=False),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "bot_id"],
            ["managed_bots.tenant_id", "managed_bots.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "payment_id"],
            ["payments.tenant_id", "payments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "plan_id"],
            ["plans.tenant_id", "plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subscriptions_contact_id"), ["contact_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscriptions_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscriptions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscriptions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_subscriptions_tenant_id"), ["tenant_id"], unique=False)

    op.create_table(
        "channel_invites",
        sa.Column("channel_id", sa.String(length=36), nullable=False),
        sa.Column("contact_id", sa.String(length=36), nullable=False),
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("invite_link", sa.String(length=512), nullable=False),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("used_at", sa.BigInteger(), nullable=True),
        sa.Column("revoked_at", sa.BigInteger(), nullable=True),
        sa.Column("tenant_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id", "channel_id"],
            ["channels.tenant_id", "channels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "contact_id"],
            ["contacts.tenant_id", "contacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "subscription_id"],
            ["subscriptions.tenant_id", "subscriptions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_link"),
        sa.UniqueConstraint("tenant_id", "id"),
    )
    with op.batch_alter_table("channel_invites", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_channel_invites_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_channel_invites_tenant_id"), ["tenant_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("channel_invites", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channel_invites_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_channel_invites_created_at"))

    op.drop_table("channel_invites")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_status"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_created_at"))
        batch_op.drop_index(batch_op.f("ix_subscriptions_contact_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("payment_charges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_charges_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payment_charges_created_at"))

    op.drop_table("payment_charges")
    with op.batch_alter_table("payment_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_attempts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payment_attempts_created_at"))

    op.drop_table("payment_attempts")
    with op.batch_alter_table("coupon_redemptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_coupon_redemptions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_coupon_redemptions_created_at"))

    op.drop_table("coupon_redemptions")
    with op.batch_alter_table("bank_receipts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bank_receipts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bank_receipts_sha256"))
        batch_op.drop_index(batch_op.f("ix_bank_receipts_payment_id"))
        batch_op.drop_index(batch_op.f("ix_bank_receipts_created_at"))

    op.drop_table("bank_receipts")
    with op.batch_alter_table("plan_prices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plan_prices_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_plan_prices_created_at"))

    op.drop_table("plan_prices")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payments_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payments_status"))
        batch_op.drop_index(batch_op.f("ix_payments_created_at"))
        batch_op.drop_index(batch_op.f("ix_payments_contact_id"))

    op.drop_table("payments")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_messages_created_at"))
        batch_op.drop_index(batch_op.f("ix_messages_conversation_id"))

    op.drop_table("messages")
    with op.batch_alter_table("referrals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_referrals_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_referrals_created_at"))

    op.drop_table("referrals")
    with op.batch_alter_table("plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_plans_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_plans_created_at"))
        batch_op.drop_index(batch_op.f("ix_plans_bot_id"))

    op.drop_table("plans")
    with op.batch_alter_table("internal_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_internal_notes_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_internal_notes_created_at"))

    op.drop_table("internal_notes")
    with op.batch_alter_table("crm_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_crm_tasks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_crm_tasks_created_at"))

    op.drop_table("crm_tasks")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_created_at"))

    op.drop_table("conversations")
    with op.batch_alter_table("contact_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_tags_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_contact_tags_created_at"))

    op.drop_table("contact_tags")
    with op.batch_alter_table("campaign_recipients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaign_recipients_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_campaign_recipients_created_at"))
        batch_op.drop_index(batch_op.f("ix_campaign_recipients_campaign_id"))

    op.drop_table("campaign_recipients")
    with op.batch_alter_table("automation_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_executions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_automation_executions_created_at"))

    op.drop_table("automation_executions")
    with op.batch_alter_table("attribution_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attribution_links_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_attribution_links_created_at"))

    op.drop_table("attribution_links")
    with op.batch_alter_table("saas_charges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saas_charges_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_saas_charges_created_at"))

    op.drop_table("saas_charges")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contacts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_contacts_stage"))
        batch_op.drop_index(batch_op.f("ix_contacts_created_at"))
        batch_op.drop_index(batch_op.f("ix_contacts_bot_id"))

    op.drop_table("contacts")
    with op.batch_alter_table("channels", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_channels_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_channels_created_at"))

    op.drop_table("channels")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_campaigns_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_campaigns_created_at"))

    op.drop_table("campaigns")
    with op.batch_alter_table("bot_texts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_texts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bot_texts_created_at"))

    op.drop_table("bot_texts")
    with op.batch_alter_table("bot_settings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_settings_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bot_settings_created_at"))

    op.drop_table("bot_settings")
    with op.batch_alter_table("bot_secrets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_secrets_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bot_secrets_created_at"))

    op.drop_table("bot_secrets")
    with op.batch_alter_table("automation_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_automation_rules_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_automation_rules_created_at"))

    op.drop_table("automation_rules")
    with op.batch_alter_table("usage_counters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_counters_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_usage_counters_created_at"))

    op.drop_table("usage_counters")
    with op.batch_alter_table("tenant_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenant_members_user_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_members_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tenant_members_created_at"))

    op.drop_table("tenant_members")
    with op.batch_alter_table("telegram_updates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telegram_updates_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_telegram_updates_created_at"))

    op.drop_table("telegram_updates")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_tags_created_at"))

    op.drop_table("tags")
    with op.batch_alter_table("saas_subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saas_subscriptions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_saas_subscriptions_created_at"))

    op.drop_table("saas_subscriptions")
    with op.batch_alter_table("saas_invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saas_invoices_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_saas_invoices_created_at"))

    op.drop_table("saas_invoices")
    with op.batch_alter_table("provider_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_provider_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_provider_events_created_at"))

    op.drop_table("provider_events")
    with op.batch_alter_table("payment_provider_configs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payment_provider_configs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_payment_provider_configs_created_at"))

    op.drop_table("payment_provider_configs")
    with op.batch_alter_table("onboarding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_onboarding_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_onboarding_created_at"))

    op.drop_table("onboarding")
    with op.batch_alter_table("managed_bots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_managed_bots_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_managed_bots_created_at"))

    op.drop_table("managed_bots")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_jobs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_jobs_created_at"))
        batch_op.drop_index("ix_job_due")

    op.drop_table("jobs")
    with op.batch_alter_table("feature_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feature_flags_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_feature_flags_created_at"))

    op.drop_table("feature_flags")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_type"))
        batch_op.drop_index(batch_op.f("ix_events_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_events_bot_id"))

    op.drop_table("events")
    with op.batch_alter_table("coupons", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_coupons_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_coupons_created_at"))

    op.drop_table("coupons")
    with op.batch_alter_table("bot_creation_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_bot_creation_requests_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_bot_creation_requests_telegram_user_id"))
        batch_op.drop_index(batch_op.f("ix_bot_creation_requests_created_at"))

    op.drop_table("bot_creation_requests")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))

    op.drop_table("audit_logs")
    with op.batch_alter_table("tenants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tenants_created_at"))

    op.drop_table("tenants")
    with op.batch_alter_table("platform_support_tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_support_tickets_created_at"))

    op.drop_table("platform_support_tickets")
    with op.batch_alter_table("auth_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_auth_sessions_expires_at"))
        batch_op.drop_index(batch_op.f("ix_auth_sessions_created_at"))

    op.drop_table("auth_sessions")
    with op.batch_alter_table("saas_plans", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_saas_plans_created_at"))

    op.drop_table("saas_plans")
    with op.batch_alter_table("platform_users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_platform_users_created_at"))

    op.drop_table("platform_users")
    # ### end Alembic commands ###
